name: GrassRPA
data:
  dsn: sqlite://data/rpa.db
  # dsn: mysql://root:123456@localhost:3306/rpa?charset=utf8mb4&parseTime=True&loc=Local
  dir: /data
http:
  port: 3080
  timeout: 15s
log:
  level: debug
redis:
  addr: localhost:6379
  password: 123456
  db: 1
